# Generated by Django 5.2.8 on 2026-02-20 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0004_invoice_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Portfolio Item', 'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('plan_name', models.CharField(max_length=100)),
                ('duration', models.CharField(default='monthly', max_length=50)),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('was_trial', models.BooleanField(default=False)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('converted', 'Trial Converted to Paid')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='creator_app.userdata')),
            ],
            options={
                'verbose_name': 'Subscription History',
                'verbose_name_plural': 'Subscription History',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='creator_app_user_id_653868_idx'), models.Index(fields=['email', 'was_trial'], name='creator_app_email_59732d_idx')],
            },
        ),
    ]
