# Generated by Django 5.2.8 on 2026-02-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0005_alter_portfolioitem_options_subscriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
