# Generated by Django 5.2.8 on 2026-02-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0006_portfolioitem_title'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscriptionhistory',
            name='creator_app_email_59732d_idx',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='trial_ended_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='trial_started_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='was_trial',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='trial_ends_at',
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='plan_id',
            field=models.IntegerField(blank=True, help_text='ID of the subscription plan', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_code',
            field=models.CharField(blank=True, help_text='Discount code for this plan', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_description',
            field=models.CharField(blank=True, help_text='Description of the discount', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='Discount percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the portfolio item', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('downgraded', 'Downgraded to Basic')], default='created', max_length=20),
        ),
        migrations.AddIndex(
            model_name='subscriptionhistory',
            index=models.Index(fields=['email'], name='creator_app_email_29b73b_idx'),
        ),
    ]
