# Generated by Django 5.2.8 on 2026-03-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0007_remove_subscriptionhistory_creator_app_email_59732d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscriptionhistory',
            name='creator_app_email_29b73b_idx',
        ),
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='plan_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='discount_code',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='discount_description',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='email_otp',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='facebook_user_id',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='facebook_verified',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='phone_otp',
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='trial_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='was_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('converted', 'Trial Converted to Paid')], default='created', max_length=20),
        ),
        migrations.AddIndex(
            model_name='subscriptionhistory',
            index=models.Index(fields=['email', 'was_trial'], name='creator_app_email_59732d_idx'),
        ),
    ]
