# Generated by Django 5.2.8 on 2026-03-03 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0008_remove_subscriptionhistory_creator_app_email_29b73b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorprofile',
            name='completed_projects',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='pricing_type',
            field=models.CharField(blank=True, default='hourly', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_year', models.CharField(max_length=20)),
                ('end_year', models.CharField(blank=True, max_length=20, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Order of display (newest first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='creator_app.userdata')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_year', models.CharField(max_length=20)),
                ('end_year', models.CharField(blank=True, max_length=20, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Order of display (newest first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='creator_app.userdata')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
