# Generated by Django 5.2.8 on 2026-03-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0009_collaboratorprofile_completed_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
