# Generated by Django 5.2.8 on 2026-03-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0010_subscriptionplan_discount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='profile_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('collaborator', 'Collaborator'), ('both', 'Both')], default='both', help_text='Which user role this plan is for', max_length=20),
        ),
    ]
