# Generated by Django 5.2.8 on 2026-03-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0013_contract_is_paid_contractworkassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorprofile',
            name='liked_jobs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='skills_required',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
