# Generated by Django 5.2.8 on 2026-04-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0014_collaboratorprofile_liked_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='has_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
