# Generated by Django 5.2.8 on 2026-04-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0015_contract_completed_at_jobpost_has_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('creator_category', 'Creator Category'), ('primary_niche', 'Primary Niche'), ('secondary_niche', 'Secondary Niche'), ('platform', 'Platform'), ('followers_range', 'Followers Range'), ('portfolio_category', 'Portfolio Category'), ('skill_category', 'Skill Category')], db_index=True, max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order', 'label'],
                'unique_together': {('category', 'value')},
            },
        ),
    ]
