# Generated by Django 5.2.8 on 2026-04-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0016_dropdownoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
    ]
