# Generated by Django 5.2.8 on 2026-04-16 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0017_rename_first_name_userdata_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('admin_profile_updated', 'Admin Profile Updated'), ('admin_password_changed', 'Admin Password Changed'), ('admin_2fa_toggled', '2FA Setting Changed'), ('admin_image_uploaded', 'Admin Image Uploaded'), ('admin_image_removed', 'Admin Image Removed'), ('admin_preferences_updated', 'Admin Preferences Updated'), ('admin_account_deleted', 'Admin Account Deleted'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_password_changed', 'User Password Changed'), ('users_exported', 'Users Data Exported'), ('new_user', 'New User Registered'), ('job_post', 'New Job Posted'), ('proposal', 'New Proposal Submitted'), ('proposal_rejected', 'Proposal Rejected'), ('payment', 'Payment Received'), ('contract_completed', 'Contract Completed'), ('password_change', 'User Password Changed')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('subtitle', models.TextField(help_text='Notification description/subtitle')),
                ('related_id', models.IntegerField(blank=True, help_text='ID of related object (user_id, job_id, etc.)', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('admin', models.ForeignKey(help_text='The admin user who should receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'db_table': 'admin_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='admin_notif_admin_i_045746_idx'), models.Index(fields=['admin', 'is_read'], name='admin_notif_admin_i_e8ff5d_idx'), models.Index(fields=['notification_type'], name='admin_notif_notific_f1a152_idx')],
            },
        ),
    ]
