# Generated by Django 5.2.8 on 2026-04-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0019_userloginactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('admin_profile_updated', 'Admin Profile Updated'), ('admin_password_changed', 'Admin Password Changed'), ('admin_2fa_toggled', '2FA Setting Changed'), ('admin_image_uploaded', 'Admin Image Uploaded'), ('admin_image_removed', 'Admin Image Removed'), ('admin_preferences_updated', 'Admin Preferences Updated'), ('admin_account_deleted', 'Admin Account Deleted'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_password_changed', 'User Password Changed'), ('users_exported', 'Users Data Exported'), ('new_user', 'New User Registered'), ('job_post', 'New Job Posted'), ('proposal', 'New Proposal Submitted'), ('proposal_rejected', 'Proposal Rejected'), ('payment', 'Payment Received'), ('contract_completed', 'Contract Completed'), ('password_change', 'User Password Changed'), ('plan_created', 'Subscription Plan Created'), ('plan_updated', 'Subscription Plan Updated'), ('plan_deleted', 'Subscription Plan Deleted')], help_text='Type of notification', max_length=50),
        ),
    ]
