# Generated by Django 5.2.8 on 2026-04-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0020_alter_adminnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='profile_image',
            field=models.CharField(blank=True, help_text='Profile image URL for the notification', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the notification was last updated'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether the notification has been read by this admin'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('admin_login', 'Admin Login'), ('admin_logout', 'Admin Logout'), ('admin_profile_updated', 'Admin Profile Updated'), ('admin_password_changed', 'Admin Password Changed'), ('admin_2fa_toggled', '2FA Setting Changed'), ('admin_image_uploaded', 'Admin Image Uploaded'), ('admin_image_removed', 'Admin Image Removed'), ('admin_preferences_updated', 'Admin Preferences Updated'), ('admin_account_deleted', 'Admin Account Deleted'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_password_changed', 'User Password Changed'), ('users_exported', 'Users Data Exported'), ('plan_created', 'Subscription Plan Created'), ('plan_updated', 'Subscription Plan Updated'), ('plan_deleted', 'Subscription Plan Deleted'), ('new_user', 'New User Registered'), ('job_post', 'New Job Posted'), ('proposal', 'New Proposal Submitted'), ('proposal_rejected', 'Proposal Rejected'), ('payment', 'Payment Received'), ('contract_completed', 'Contract Completed'), ('password_change', 'User Password Changed')], help_text='Type of notification', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='related_id',
            field=models.IntegerField(blank=True, help_text='ID of related object (user_id, job_id, proposal_id, etc.)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='adminnotification',
            unique_together={('admin', 'notification_type', 'related_id')},
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['admin', 'notification_type', 'related_id'], name='admin_notif_admin_i_b33832_idx'),
        ),
    ]
