# Generated by Django 5.2.8 on 2026-05-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0022_remove_adminnotification_admin_notif_admin_i_b33832_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='external_file_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_bytes', models.BigIntegerField(default=0, help_text='Current storage used in bytes')),
                ('limit_bytes', models.BigIntegerField(default=0, help_text='Storage limit from current plan in bytes')),
                ('used_gb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('limit_gb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('plan_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of the plan when last updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_tracking', to='creator_app.userdata')),
            ],
            options={
                'verbose_name': 'User Storage',
                'verbose_name_plural': 'User Storage',
                'indexes': [models.Index(fields=['user', 'used_bytes'], name='creator_app_user_id_4adbb1_idx')],
            },
        ),
    ]
