# Generated by Django 5.2.8 on 2026-05-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0023_contract_external_file_link_userstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='cashfree_beneficiary_id',
            field=models.CharField(blank=True, help_text='Cashfree Payout beneficiary ID for wallet withdrawals', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='withdrawal_methods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
