# Generated by Django 5.2.8 on 2026-05-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0024_userdata_cashfree_beneficiary_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='creator_app.contract'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'contract')},
        ),
    ]
