# Generated by Django 5.2.8 on 2026-05-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0025_alter_review_unique_together_review_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='revision_description',
            field=models.TextField(blank=True, help_text="Creator's feedback when requesting revision", null=True),
        ),
    ]
