# Generated by Django 5.2.8 on 2026-05-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0026_contract_revision_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionhistory',
            name='plan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='stripe_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('renewed', 'Renewed'), ('updated', 'Updated'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('downgraded', 'Downgraded'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('converted', 'Trial Converted to Paid')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='subscriptionhistory',
            index=models.Index(fields=['user', 'stripe_subscription_id'], name='creator_app_user_id_28542b_idx'),
        ),
    ]
