# Generated by Django 5.2.8 on 2026-05-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0027_subscriptionhistory_plan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
