# Generated by Django 5.2.8 on 2026-05-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0028_alter_subscriptionhistory_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='duration_days',
            field=models.IntegerField(blank=True, default=0, help_text='Duration in days (auto-calculated)', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting', 'Awaiting'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='duration',
            field=models.CharField(choices=[('1 Day', '1 Day'), ('2 Days', '2 Days'), ('3 Days', '3 Days'), ('4 Days', '4 Days'), ('5 Days', '5 Days'), ('6 Days', '6 Days'), ('7 Days', '7 Days'), ('14 Days', '14 Days'), ('21 Days', '21 Days'), ('30 Days', '30 Days'), ('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('1 Month', '1 Month'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('5 Months', '5 Months'), ('6 Months', '6 Months'), ('7 Months', '7 Months'), ('8 Months', '8 Months'), ('9 Months', '9 Months'), ('10 Months', '10 Months'), ('11 Months', '11 Months'), ('12 Months', '12 Months'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years')], max_length=50),
        ),
    ]
