# Generated by Django 5.2.8 on 2026-05-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0029_jobpost_duration_days_alter_contract_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status_reason',
            field=models.TextField(blank=True, help_text='Reason provided when setting status to pending or cancelled', null=True),
        ),
    ]
