# Generated by Django 5.2.8 on 2026-05-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0030_contract_status_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='pricing_type',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='pricing_unit',
        ),
        migrations.AlterField(
            model_name='collaboratorprofile',
            name='pricing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price for the project/service', max_digits=10, null=True),
        ),
    ]
