# Generated by Django 5.2.8 on 2026-05-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0031_remove_collaboratorprofile_pricing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='pricing_amount',
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget per project', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget per project', max_digits=10, null=True),
        ),
    ]
