# Generated by Django 5.2.8 on 2026-05-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0032_remove_collaboratorprofile_pricing_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='collaboratorprofile',
            name='budget_min',
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='pricing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='pricing_type',
            field=models.CharField(blank=True, default='hourly', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='pricing_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
