# Generated by Django 5.2.8 on 2026-05-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0033_remove_collaboratorprofile_budget_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='heading',
            field=models.CharField(blank=True, help_text='Work name/title', max_length=255, null=True),
        ),
    ]
