# Generated by Django 5.2.8 on 2026-05-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0034_portfolioitem_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='current_milestone',
            field=models.IntegerField(default=0, help_text='Index of current active milestone (0-based)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='milestones_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='proposal',
            name='milestones_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
