# Generated by Django 5.2.8 on 2026-05-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0035_contract_current_milestone_contract_milestones_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='plan_expires_at',
            new_name='canceled_at',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan_started_at',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
