# Generated by Django 5.2.8 on 2026-05-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0036_rename_plan_expires_at_usersubscription_canceled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='state',
        ),
        migrations.AddField(
            model_name='collaboratorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
