# Generated by Django 5.2.8 on 2026-06-01 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0037_remove_userdata_address_remove_userdata_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='creator_app.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator_app.userdata')),
            ],
            options={
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
    ]
