# Generated by Django 5.2.8 on 2026-06-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0038_message_edited_messagereaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='role',
            field=models.CharField(blank=True, choices=[('creator', 'Creator'), ('collaborator', 'Collaborator')], help_text='Which user role this plan is for', max_length=20, null=True),
        ),
    ]
