# Generated by Django 5.2.8 on 2026-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0040_message_is_starred_message_starred_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropdownoption',
            options={'ordering': ['category', 'label']},
        ),
        migrations.AlterUniqueTogether(
            name='dropdownoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userdata',
            name='total_contracts_created',
            field=models.IntegerField(default=0, help_text='Total contracts ever created'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='total_invitations_sent',
            field=models.IntegerField(default=0, help_text='Total invitations ever sent'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='total_jobs_created',
            field=models.IntegerField(default=0, help_text='Total jobs ever created'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='total_proposals_created',
            field=models.IntegerField(default=0, help_text='Total proposals ever created'),
        ),
        migrations.RemoveField(
            model_name='dropdownoption',
            name='order',
        ),
        migrations.RemoveField(
            model_name='dropdownoption',
            name='value',
        ),
    ]
