# Generated by Django 5.2.8 on 2026-06-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0041_alter_dropdownoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
